package nl.hva.ict.ads;

import java.util.Random;

/**
 * Just a helper class for generating random names for the archers.
 */
public class Names {
    private static Random randomizer = new Random();

    public static void reSeed(long seed) {
        randomizer = new Random(seed);
    }
    public static String nextFirstName() {
        return firstNames[randomizer.nextInt(firstNames.length)];
    }

    public static String nextSurname() {
        return surnames[randomizer.nextInt(surnames.length)];
    }

    private static String[] firstNames = {
            "James", "Mary",
            "John", "Patricia",
            "Robert", "Jennifer",
            "Michael", "Linda",
            "William", "Elizabeth",
            "David", "Barbara",
            "Richard", "Susan",
            "Joseph", "Jessica",
            "Thomas", "Sarah",
            "Charles", "Karen",
            "Christopher", "Nancy",
            "Daniel", "Margaret",
            "Matthew", "Lisa",
            "Anthony", "Betty",
            "Donald", "Dorothy",
            "Mark", "Sandra",
            "Paul", "Ashley",
            "Steven", "Kimberly",
            "Andrew", "Donna",
            "Kenneth", "Emily",
            "Joshua", "Michelle",
            "George", "Carol",
            "Kevin", "Amanda",
            "Brian", "Melissa",
            "Edward", "Deborah",
            "Ronald", "Stephanie",
            "Timothy", "Rebecca",
            "Jason", "Laura",
            "Jeffrey", "Sharon",
            "Ryan", "Cynthia",
            "Jacob", "Kathleen",
            "Gary", "Helen",
            "Nicholas", "Amy",
            "Eric", "Shirley",
            "Stephen", "Angela",
            "Jonathan", "Anna",
            "Larry", "Brenda",
            "Justin", "Pamela",
            "Scott", "Nicole",
            "Brandon", "Ruth",
            "Frank", "Katherine",
            "Benjamin", "Samantha",
            "Gregory", "Christine",
            "Samuel", "Emma",
            "Raymond", "Catherine",
            "Patrick", "Debra",
            "Alexander", "Virginia",
            "Jack", "Rachel",
            "Dennis", "Carolyn",
            "Jerry", "Janet",
            "Tyler", "Maria",
            "Aaron", "Heather",
            "Jose", "Diane",
            "Henry", "Julie",
            "Douglas", "Joyce",
            "Adam", "Victoria",
            "Peter", "Kelly",
            "Nathan", "Christina",
            "Zachary", "Joan",
            "Walter", "Evelyn",
            "Kyle", "Lauren",
            "Harold", "Judith",
            "Carl", "Olivia",
            "Jeremy", "Frances",
            "Keith", "Martha",
            "Roger", "Cheryl",
            "Gerald", "Megan",
            "Ethan", "Andrea",
            "Arthur", "Hannah",
            "Terry", "Jacqueline",
            "Christian", "Ann",
            "Sean", "Jean",
            "Lawrence", "Alice",
            "Austin", "Kathryn",
            "Joe", "Gloria",
            "Noah", "Teresa",
            "Jesse", "Doris",
            "Albert", "Sara",
            "Bryan", "Janice",
            "Billy", "Julia",
            "Bruce", "Marie",
            "Willie", "Madison",
            "Jordan", "Grace",
            "Dylan", "Judy",
            "Alan", "Theresa",
            "Ralph", "Beverly",
            "Gabriel", "Denise",
            "Roy", "Marilyn",
            "Juan", "Amber",
            "Wayne", "Danielle",
            "Eugene", "Abigail",
            "Logan", "Brittany",
            "Randy", "Rose",
            "Louis", "Diana",
            "Russell", "Natalie",
            "Vincent", "Sophia",
            "Philip", "Alexis",
            "Bobby", "Lori",
            "Johnny", "Kayla",
            "Bradley", "Jane",
    };

    private static String[] surnames = {

            "SMITH",
            "JOHNSON",
            "WILLIAMS",
            "JONES",
            "BROWN",
            "DAVIS",
            "MILLER",
            "WILSON",
            "MOORE",
            "TAYLOR",
            "ANDERSON",
            "THOMAS",
            "JACKSON",
            "WHITE",
            "HARRIS",
            "MARTIN",
            "THOMPSON",
            "GARCIA",
            "MARTINEZ",
            "ROBINSON",
            "CLARK",
            "RODRIGUEZ",
            "LEWIS",
            "LEE",
            "WALKER",
            "HALL",
            "ALLEN",
            "YOUNG",
            "HERNANDEZ",
            "KING",
            "WRIGHT",
            "LOPEZ",
            "HILL",
            "SCOTT",
            "GREEN",
            "ADAMS",
            "BAKER",
            "GONZALEZ",
            "NELSON",
            "CARTER",
            "MITCHELL",
            "PEREZ",
            "ROBERTS",
            "TURNER",
            "PHILLIPS",
            "CAMPBELL",
            "PARKER",
            "EVANS",
            "EDWARDS",
            "COLLINS",
            "STEWART",
            "SANCHEZ",
            "MORRIS",
            "ROGERS",
            "REED",
            "COOK",
            "MORGAN",
            "BELL",
            "MURPHY",
            "BAILEY",
            "RIVERA",
            "COOPER",
            "RICHARDSON",
            "COX",
            "HOWARD",
            "WARD",
            "TORRES",
            "PETERSON",
            "GRAY",
            "RAMIREZ",
            "JAMES",
            "WATSON",
            "BROOKS",
            "KELLY",
            "SANDERS",
            "PRICE",
            "BENNETT",
            "WOOD",
            "BARNES",
            "ROSS",
            "HENDERSON",
            "COLEMAN",
            "JENKINS",
            "PERRY",
            "POWELL",
            "LONG",
            "PATTERSON",
            "HUGHES",
            "FLORES",
            "WASHINGTON",
            "BUTLER",
            "SIMMONS",
            "FOSTER",
            "GONZALES",
            "BRYANT",
            "ALEXANDER",
            "RUSSELL",
            "GRIFFIN",
            "DIAZ",
            "HAYES",
            "MYERS",
            "FORD",
            "HAMILTON",
            "GRAHAM",
            "SULLIVAN",
            "WALLACE",
            "WOODS",
            "COLE",
            "WEST",
            "JORDAN",
            "OWENS",
            "REYNOLDS",
            "FISHER",
            "ELLIS",
            "HARRISON",
            "GIBSON",
            "MCDONALD",
            "CRUZ",
            "MARSHALL",
            "ORTIZ",
            "GOMEZ",
            "MURRAY",
            "FREEMAN",
            "WELLS",
            "WEBB",
            "SIMPSON",
            "STEVENS",
            "TUCKER",
            "PORTER",
            "HUNTER",
            "HICKS",
            "CRAWFORD",
            "HENRY",
            "BOYD",
            "MASON",
            "MORALES",
            "KENNEDY",
            "WARREN",
            "DIXON",
            "RAMOS",
            "REYES",
            "BURNS",
            "GORDON",
            "SHAW",
            "HOLMES",
            "RICE",
            "ROBERTSON",
            "HUNT",
            "BLACK",
            "DANIELS",
            "PALMER",
            "MILLS",
            "NICHOLS",
            "GRANT",
            "KNIGHT",
            "FERGUSON",
            "ROSE",
            "STONE",
            "HAWKINS",
            "DUNN",
            "PERKINS",
            "HUDSON",
            "SPENCER",
            "GARDNER",
            "STEPHENS",
            "PAYNE",
            "PIERCE",
            "BERRY",
            "MATTHEWS",
            "ARNOLD",
            "WAGNER",
            "WILLIS",
            "RAY",
            "WATKINS",
            "OLSON",
            "CARROLL",
            "DUNCAN",
            "SNYDER",
            "HART",
            "CUNNINGHAM",
            "BRADLEY",
            "LANE",
            "ANDREWS",
            "RUIZ",
            "HARPER",
            "FOX",
            "RILEY",
            "ARMSTRONG",
            "CARPENTER",
            "WEAVER",
            "GREENE",
            "LAWRENCE",
            "ELLIOTT",
            "CHAVEZ",
            "SIMS",
            "AUSTIN",
            "PETERS",
            "KELLEY",
            "FRANKLIN",
            "LAWSON",
            "FIELDS",
            "GUTIERREZ",
            "RYAN",
            "SCHMIDT",
            "CARR",
            "VASQUEZ",
            "CASTILLO",
            "WHEELER",
            "CHAPMAN",
            "OLIVER",
            "MONTGOMERY",
            "RICHARDS",
            "WILLIAMSON",
            "JOHNSTON",
            "BANKS",
            "MEYER",
            "BISHOP",
            "MCCOY",
            "HOWELL",
            "ALVAREZ",
            "MORRISON",
            "HANSEN",
            "FERNANDEZ",
            "GARZA",
            "HARVEY",
            "LITTLE",
            "BURTON",
            "STANLEY",
            "NGUYEN",
            "GEORGE",
            "JACOBS",
            "REID",
            "KIM",
            "FULLER",
            "LYNCH",
            "DEAN",
            "GILBERT",
            "GARRETT",
            "ROMERO",
            "WELCH",
            "LARSON",
            "FRAZIER",
            "BURKE",
            "HANSON",
            "DAY",
            "MENDOZA",
            "MORENO",
            "BOWMAN",
            "MEDINA",
            "FOWLER",
            "BREWER",
            "HOFFMAN",
            "CARLSON",
            "SILVA",
            "PEARSON",
            "HOLLAND",
            "DOUGLAS",
            "FLEMING",
            "JENSEN",
            "VARGAS",
            "BYRD",
            "DAVIDSON",
            "HOPKINS",
            "MAY",
            "TERRY",
            "HERRERA",
            "WADE",
    };

}
